version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    command: 
      --innodb-use-native-aio=0
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: designs-dev-db.credhjaqdcgx.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_password
      WORDPRESS_DB_NAME: unlockb2b
      WORDPRESS_CONFIG_EXTRA: 
volumes:
  db_data: