name: Create Pipeline & Application

on:
  create:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Create artifact
          run: cd ./wp/wp-content && ls && cd ../..
        - name: Create application
          run: aws deploy create-application --cli-input-json file://${{github.workspace}}/application.json --region us-east-1
          env:
            AWS_S3_BUCKET: 'designs-dev-pipeline-artifacts'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Creeate deployment group
          run: aws deploy create-deployment-group --cli-input-json file://${{github.workspace}}/deployment-group.json --region us-east-1
          env:
            AWS_S3_BUCKET: 'designs-dev-pipeline-artifacts'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Create pipeline
          run: aws codepipeline create-pipeline --cli-input-json file://${{github.workspace}}/pipeline.json --region us-east-1
          env:
            AWS_S3_BUCKET: 'designs-dev-pipeline-artifacts'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}